import {
  ShoppingCart,
  ShoppingBag,
  Car,
  Bus,
  Train,
  Plane,
  Bike,
  Fuel,
  Utensils,
  Coffee,
  Pizza,
  House,
  Building2,
  Hotel,
  Wifi,
  Zap,
  Droplets,
  Flame,
  Phone,
  Smartphone,
  Laptop,
  Monitor,
  Tv,
  Gamepad2,
  Music,
  Film,
  Book,
  BookOpen,
  GraduationCap,
  Briefcase,
  Building,
  Store,
  Wallet,
  PiggyBank,
  CreditCard,
  Banknote,
  Coins,
  HandCoins,
  TrendingUp,
  Gift,
  Heart,
  HeartPulse,
  Stethoscope,
  Pill,
  Dumbbell,
  Shirt,
  Baby,
  Dog,
  Cat,
  Palette,
  Camera,
  Scissors,
  Wrench,
  Leaf,
  Sun,
  Umbrella,
  Ticket,
  Receipt,
  DollarSign,
  Star,
  Target,
  Trophy,
  Rocket,
  Flag,
  Tag,
  type LucideIcon,
} from "lucide-react";

/**
 * Registre d'icônes pour les catégories.
 * Les clés sont des noms Lucide en kebab-case (compatibles avec le seed).
 */
export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  car: Car,
  bus: Bus,
  train: Train,
  plane: Plane,
  bike: Bike,
  fuel: Fuel,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  house: House,
  home: House, // alias historique (Lucide a renommé Home → House)
  "building-2": Building2,
  hotel: Hotel,
  wifi: Wifi,
  zap: Zap,
  droplets: Droplets,
  flame: Flame,
  phone: Phone,
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  tv: Tv,
  "gamepad-2": Gamepad2,
  music: Music,
  film: Film,
  book: Book,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  building: Building,
  store: Store,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  banknote: Banknote,
  coins: Coins,
  "hand-coins": HandCoins,
  "trending-up": TrendingUp,
  gift: Gift,
  heart: Heart,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  shirt: Shirt,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  palette: Palette,
  camera: Camera,
  scissors: Scissors,
  wrench: Wrench,
  leaf: Leaf,
  sun: Sun,
  umbrella: Umbrella,
  ticket: Ticket,
  receipt: Receipt,
  "dollar-sign": DollarSign,
  star: Star,
  target: Target,
  trophy: Trophy,
  rocket: Rocket,
  flag: Flag,
  tag: Tag,
};

/** Noms d'icônes proposés dans le sélecteur (hors alias). */
export const CATEGORY_ICON_NAMES: string[] = Object.keys(CATEGORY_ICON_MAP).filter(
  (name) => name !== "home",
);

/** Résout un nom d'icône en composant Lucide (fallback : `Tag`). */
export function getCategoryIcon(name?: string | null): LucideIcon {
  if (name && CATEGORY_ICON_MAP[name]) return CATEGORY_ICON_MAP[name];
  return Tag;
}
